### ISSUE TITLE
Quickpick doesn't run at all in windows 10

### ISSUE THREAD

**Issue by tlkw79** [rrskybox/QuickPick#1]
After double click on the .exe file, nothing happens.

**Comment by tlkw79** [comment]
Actually it install successfully. Just when I click on Quick pick Exe file, nothing happens.

**Comment by rrskybox** [comment]
My bad.  I was porting this app from Visual Basic to C# and got about half done.  I will update here when I've got it running again.

**Comment by rrskybox** [comment]
Finished the port.  Should be reasonably solid.  Remember that you must have Microsoft Visual Basic Power Packs 3.0 installed for the graphics to work: [https://www.microsoft.com/en-us/download/details.aspx?id=25169](url)

**Comment by tlkw79** [comment]
That is great. Just the application startup a bit slow. Thanks a lot.

**Comment by rrskybox** [comment]
Yeah, it spends some time getting TSX up, then running and downloading a TSX observation list query which is inherently slow.  Can't fix much there...
