### ISSUE TITLE
Does not compile Error Enclosed.

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/QuickPick#2]
Here is a picture of the error it throws.. Looks like a old call to skyx maybe...
![Error Compile](https://user-images.githubusercontent.com/14363854/218862831-d05d731a-d9cb-4603-af32-fbb32dcc2c73.jpg)

**Comment by rrskybox** [comment]
Yeah, QuickPick is a pretty old program -- one of the first I wrote for TSX.  Mostly as an exercise to learn how to program Observing List based functions and play around with Windows Drawing.  Never got around to recompiling it for TheSky64.  I'll get that done and post the zips in Publish.

**Comment by rrskybox** [comment]
Updated for 32 and 64 bit installation packages.

**Comment by astromiester1** [comment]
I used the 64bit version but when I run in win10, nothing displays... Similar behavior from other closed thread on win10 not running the program.. Just an Fyi...

**Comment by astromiester1** [comment]
I went back in VS to compile I get the same error again shown above. This is after I installed the Microsoft Visual Basic Power Packs in the tools Nuget area. At first, when opening the project, it reports the power pack library is not installed with errors on compile. Once, I installed the package, the errors went away and when compiled I get this new error from Sky6DataWizard object...

**Comment by rrskybox** [comment]
I failed to get rid of one reference to the TSX 32 bit library in the 64 bit compile so the app was trying to bring up TSX 32 and failing.  That's been corrected in the latest 64 bit installation (Build 9).  That is also the reason behind the DataWizard object error.

I'm not sure what's going on with the VB Power Packs.  The original version of this was in VB, but no longer.  Might just be a VS porting problem.

To be honest, though, QuickPick has been largely supplanted by Image Planner.  It probably doesn't warrant spending much more time on.  Same in general with TSX32 versions.  I've only gotten one or two requests for TSX32 versions of anything anymore so I'll probably just compile them as requested.  It's a pain in the ass to maintain two versions.

**Comment by astromiester1** [comment]
Got ya.. It works now fyi....Thanks Dale
